name: Beautify

on:
  push:
    branches:
      - master
    paths:
      - '**.py'

jobs:
  beautify:
    name: Beautify code
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Format code
        run: |
          python -m pip install black
          python -m black .
      - name: Sort imports
        run: |
          python -m pip install "isort >=5,<6"
          python -m isort --src ribbot/ --profile black .

      - name: Commit and push changes
        uses: github-actions-x/commit@v2.5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'Beautify code'
          name: github-actions
          email: action@github.com
