name: Release

on:
  push:
    branches:
      - master

jobs:
  beautify:
    name: Beautify code
    runs-on: ubuntu-latest
    outputs:
      new_sha: ${{ steps.sha.outputs.SHA }}

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Format code
        run: |
          python -m pip install black
          python -m black .
      - name: Sort imports
        run: |
          python -m pip install "isort >=5,<6"
          python -m isort --src ribbot/ --profile black .

      - name: Commit and push changes
        uses: github-actions-x/commit@v2.5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'Beautify code'
          name: github-actions
          email: action@github.com

      - name: Get new SHA
        id: sha
        run: |
          new_sha=$(git rev-parse HEAD)
          echo "::set-output name=SHA::$new_sha"

  release:
    name: Semantic Release
    runs-on: ubuntu-latest
    needs: [beautify]
    if: github.repository == 'josphh/ribbot'

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: ${{ needs.beautify.outputs.new_sha }}
    - name: Fetch master
      run: git fetch --prune origin +refs/heads/master:refs/remotes/origin/master

    - name: Python Semantic Release
      uses: relekang/python-semantic-release@v7.4.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
